POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "jan@example.org",
  "password": "personal"
}

###
// @no-redirect
POST http://localhost:8080/login
Content-Type: application/json

{
"username": "jan@example.org",
"password": "personal"
}

###
GET http://localhost:8080/orders/9