version: '3.1'

services:
  db:
    container_name: letsdrivedb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: letsdrive
      POSTGRES_USER: slupi
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432

